### ISSUE TITLE
Header Error

### ISSUE THREAD

**Issue by vishalgautam** [sebastiandev/zipper#1]
Hi Sebastian
I am using your code for zipping the folder which have images . But during extracting from zip files it gives me header . could you please help me what is the issue .

**Comment by sebastiandev** [comment]
Sure! Please send me the code where you are using zipper and i'll take a
look.

**Comment by sebastiandev** [comment]
@vishalgautam did you solve the problem? are you still experiencing issues? please let me know or I'll close this.

thanks!
