### ISSUE TITLE
Stuck when adding files to a password protected zip file on WSL Ubuntu

### ISSUE THREAD

**Issue by BullyWiiPlaza** [sebastiandev/zipper#102]
Here's a simple example code reproducing the issue:
```
#include <zipper/zipper.h>

using namespace zipper;

#include <fstream>

int main() {
	try {
		std::ifstream input1("../Test1.txt");
		if (input1.fail()) {
			throw std::runtime_error("Cannot open input file 1");
		}
		std::ifstream input2("../Test2.txt");
		if (input2.fail()) {
			throw std::runtime_error("Cannot open input file 2");
		}

		std::cout << "Zipper example" << std::endl;
		Zipper zipper("ziptest2.zip", "123456");
		std::cout << "Input1" << std::endl;
		zipper.add(input1, "Test1");
		std::cout << "Input2" << std::endl;
		zipper.add(input2, "Test2");
		std::cout << "Finished" << std::endl;
	}
	catch (std::exception &exception) {
		std::cerr << exception.what() << std::endl;
	}
}
```
Project file system structure:
![image](https://user-images.githubusercontent.com/7620135/126775270-5e2fbe62-4400-4aaa-a2cc-b05823d79ecb.png)
Output:
```
Zipper example
Input1
```
Here it does not continue. When the code execution is stuck, I can pause the code execution to see the stack trace of where it is stuck:
![image](https://user-images.githubusercontent.com/7620135/126775351-9d22fa90-ba53-4bf6-8327-2888d078c452.png)

The main culprit seems to be the following while loop which is incredibly slow:
![image](https://user-images.githubusercontent.com/7620135/126775528-d5cb03cf-9929-4dd5-90ba-bf2636cbb592.png)
Any ideas how this issue could be fixed? Not using a zip password works just fine. I tested the same code on Windows and it worked just fine with a zip password or without.

**Comment by Lecrapouille** [comment]
Hi! I'm currently on holidays your code seems ok on a Mac OS X (not my personal desktop) on the master branch, and on my side I succeeded to zip all files:
```
Zipper example
Input1
Input2
Finished
```

But I could not succeeded to unzip with the zipper of Mac OS X. Are you testing the master or dev branch ?

**Comment by BullyWiiPlaza** [comment]
Hi, I'm using the commit https://github.com/sebastiandev/zipper/commit/155e17347b64f7182985a2772ebb179184e4f518 which is on the master branch. Maybe this issue only occurs on Linux then. You could quite easily try it on a Ubuntu VM as well I guess.

**Comment by Lecrapouille** [comment]
Sorry for the long delay I just tried now on my personal Debian on the develop branch, this is working perfectly on my side. I guess a different algorithm is used with an incompatible version of one wrapped lib.

**Comment by Lecrapouille** [comment]
@BullyWiiPlaza Have you the same issue with the v2.x.y branch ? https://github.com/sebastiandev/zipper/tree/v2.x.y I have included your code in unit tests and I have no more issue for Linux and MacOS. I'll stop maintaining the master branch. Please reopen this ticket in case of.
