### ISSUE TITLE
Zip not updated if already exists

### ISSUE THREAD

**Issue by ElisaTartarini** [sebastiandev/zipper#103]
If a new Zipper object is created from an existing path and then files are added with names that are already in the zip, the add operation has no effect.

Should it be possible to pass in the flags to the constructor instead of setting them always to Zipper::Append?
https://github.com/sebastiandev/zipper/blob/201627bd3dbfbf1b53f69af29b8b079a9f3ffb1c/zipper/zipper.cpp#L38-L43

**Comment by ElisaTartarini** [comment]
EDIT: the file is added but duplicated. And when extracted with Archive Utility on mac, only one of the duplicate entry is extracted

![Screenshot 2021-08-10 at 14 34 08](https://user-images.githubusercontent.com/16403926/128867850-6c7053bd-da90-4012-8b88-9ade0cbd4453.png)

![Screenshot 2021-08-10 at 14 35 33](https://user-images.githubusercontent.com/16403926/128867865-80d6ee29-eb77-4756-a4f0-b1a3b9cfd4bd.png)

**Comment by Lecrapouille** [comment]
As far I knew this lib this was the behavior. See https://github.com/sebastiandev/zipper/issues/58

**Comment by Lecrapouille** [comment]
And for passing flags I wanted to do it but the tricky part is explained here https://github.com/sebastiandev/zipper/issues/89

**Comment by Lecrapouille** [comment]
@ElisaTartarini I committed something in the develop branch. I hope I broke nothing. Feel free to open this ticket back if something is not good.
