### ISSUE TITLE
Update to Zlib outdated versions

### ISSUE THREAD

**Issue by Lecrapouille** [sebastiandev/zipper#105]
@Togtja on the dev branch we are referring to the Zlib master branch which is no longer maintained. Their dev branch has major fixes included, but some are missing (for example https://github.com/madler/zlib/pull/393) can we refer to this dev branch branch and apply some of their fixes ? Ideally would be better to refer and always follow this Zlib https://github.com/zlib-ng/zlib-ng

Referring to https://github.com/sebastiandev/zipper/issues/33

**Comment by Lecrapouille** [comment]
I have forked the zlib create a develop-fixes branches from the develop branch and patch with some PR with this method https://coderwall.com/p/6aw72a/creating-patch-from-github-pull-request

**Comment by Lecrapouille** [comment]
@Togtja I have created the branch `dev-ng` using the submodule referring to `zlib-ng` it seems ok. I also forced zlib-ng to stop using namespace -ng and I forced Zipper to compiled zlib-ng. But I find that odd that cmake .. is building zlib-ng directly. Anyway, I'm really bored of CMake syntax.

**Comment by Togtja** [comment]
I can take a look, one of the issues I have had with zlib and submodules is that it renames `zconf.h`, I did create a pull request in the original library about this.
https://github.com/madler/zlib/pull/519/files

**Comment by Lecrapouille** [comment]
@Togtja sadly this project is dead, on our Zipper development branch, I changed the submodules to refer to my fork refering to their dev branch + some patches. So I can include yours. But the zlib-ng new generation seems to work well so I would like to force compiling Zipper with this one for any OS. At least to follow 1 lib updated (upon 2 since minizip seems more complicated).

**Comment by Lecrapouille** [comment]
> I can take a look, one of the issues I have had with zlib and submodules is that it renames `zconf.h`, I did create a pull request in the original library about this.
> https://github.com/madler/zlib/pull/519/files

@Togtja Updated on our developement branch

**Comment by Neustradamus** [comment]
It will be nice to be compatible with original zlib and zlib-ng and original minizip and minizip-ng:

Original MiniZip place:
- https://www.winimage.com/zLibDll/minizip.html

zlib master branch:
- https://github.com/madler/zlib/
- https://github.com/madler/zlib/tree/master/contrib/minizip

zlib develop branch:
- https://github.com/madler/zlib/tree/develop
- https://github.com/madler/zlib/tree/develop/contrib/minizip

You can support:
- zlib + minizip
or
- zlib-ng + minizip-ng

NG:
- zlib-ng: https://github.com/zlib-ng/zlib-ng
- minizip-ng: https://github.com/zlib-ng/minizip-ng

Linked to:
- https://github.com/sebastiandev/zipper/issues/110
- https://github.com/sebastiandev/zipper/issues/105
- https://github.com/sebastiandev/zipper/issues/106
- https://github.com/zlib-ng/minizip-ng/issues/358

**Comment by Lecrapouille** [comment]
Closing since the branch v2.x is tracking the HEAD of the minizip-ng and I'll no longer maintain the master branch.

**Comment by Neustradamus** [comment]
@Lecrapouille: For information, please look upstream.

**Comment by Lecrapouille** [comment]
@Neustradamus Sorry I did not understand your question. What exactly I have to look for ? git upstream ?

**Comment by Neustradamus** [comment]
@Lecrapouille: Here: https://github.com/madler/zlib/pull/393.

**Comment by Lecrapouille** [comment]
@Neustradamus I'm tracking zlib-ng HEAD in the v2.x branch (that is now https://github.com/Lecrapouille/zipper). See https://github.com/Lecrapouille/zipper/blob/master/external/download-external-libs.sh

I'm no longer updating this current repo (master or v2.x). I fixed 99% of all opened tickets in the v2.x, I replaced catch by something more serious: gtest. I simplified number of files. I had to break the API compatibility to manage the security fix and I swapped to my Makefile because 99% of tickets were focused on CMake and Windows 2 things I hate the most in the world, so I could not help :) Switching to my Makefile made me discovered some issues. The main issue is my Makefile is not working for Windows (but now for my job I have a Windows, so I can fix it, like switching to Python). You can a PR to add CMake back if you want. Concerning the v2.x versus main: it's up to the original author choice, since APIs are no longer compatible. Currently, because of my new job, I have less energy to keep developing in GitHub on nights.
