### ISSUE TITLE
Update to Minizip outdated versions

### ISSUE THREAD

**Issue by Lecrapouille** [sebastiandev/zipper#106]

**Comment by Neustradamus** [comment]
It will be nice to be compatible with original zlib and zlib-ng and original minizip and minizip-ng:

Original MiniZip place:
- https://www.winimage.com/zLibDll/minizip.html

zlib master branch:
- https://github.com/madler/zlib/
- https://github.com/madler/zlib/tree/master/contrib/minizip

zlib develop branch:
- https://github.com/madler/zlib/tree/develop
- https://github.com/madler/zlib/tree/develop/contrib/minizip

You can support:
- zlib + minizip
or
- zlib-ng + minizip-ng

NG:
- zlib-ng: https://github.com/zlib-ng/zlib-ng
- minizip-ng: https://github.com/zlib-ng/minizip-ng

Linked to:
- https://github.com/sebastiandev/zipper/issues/110
- https://github.com/sebastiandev/zipper/issues/105
- https://github.com/sebastiandev/zipper/issues/106
- https://github.com/zlib-ng/minizip-ng/issues/358

**Comment by Lecrapouille** [comment]
https://github.com/Lecrapouille/zipper
