### ISSUE TITLE
Do not mix zlib and zlib-ng and minizip (included in zlib) and minizip-ng

### ISSUE THREAD

**Issue by Neustradamus** [sebastiandev/zipper#110]
@sebastiandev: In first, I wish you a Happy New Year!

Please do not mix zlib and zlib-ng and minizip (included in zlib) and minizip-ng.

Currently submodules are not good!

Original MiniZip place:
- https://www.winimage.com/zLibDll/minizip.html

zlib master branch:
- https://github.com/madler/zlib/
- https://github.com/madler/zlib/tree/master/contrib/minizip

zlib develop branch:
- https://github.com/madler/zlib/tree/develop
- https://github.com/madler/zlib/tree/develop/contrib/minizip

You can support:
- zlib + minizip
or
- zlib-ng + minizip-ng

Thanks in advance.

**Comment by Lecrapouille** [comment]
@Neustradamus, sebatian never replies, and make a long time I did not dev on this lib but from my memory zipper used zlib which is 10 years old. I succeeded to climb some years on the git history of the dev branch of zlib (our master branch) but after zlib becomes not compatible with our code. The dev-ng version is an attempt to use an up to date versions. I was preparing the v2 a cleaner version of zipper and wanted to merge with the dev-ng and dev-modernize but I spent not enough time on this lib. I'll try on the next week. And in addition I cannot fix the ZipSlip attack without braking the API. What I think I'll do: keep developing the v2 branch, keep accepting pull requests for the master branch. When the v2 will be ready, I'll probably archive this repo and create my own repo.

**Comment by Neustradamus** [comment]
@Lecrapouille: If @sebastiandev has stopped to work on Zipper, it is not possible to move the repo in a better place instead of a fork creation?

@sebastiandev, it is possible to do a transfer in an organization to have a good future for Zipper?

Thanks in advance.

**Comment by Neustradamus** [comment]
@sebastiandev: It is possible to have some news from you?
