### ISSUE TITLE
unzipper.cpp extractAll can be refined

### ISSUE THREAD

**Issue by YJMLWZ** [sebastiandev/zipper#112]
locateEntry takes too much time when the entires number is big. e.g. when there are 10000+ entries there. it take huge amount of time to locateEntry.

improvement can be:
goto first file. and do extract
then gotoNext file and do extract until the last, 

in my case unzip time improved from 60 seconds to 3 seconds.

**Comment by Lecrapouille** [comment]
@YJMLWZ Thank you ! Can you do a pull request ?
