### ISSUE TITLE
What do I need to change to compile a static lib for Mac universal build?

### ISSUE THREAD

**Issue by potterpg** [sebastiandev/zipper#113]
What do I need to change to compile a static lib for Mac universal build?

in CMake I set the variable CMAKE_OSX_ARCHITECTURES to arm64 x86_64
It seems to compile and generate the lib, but the Arm64 has missing symbols exported, so unusable.

Its probably some simple flag, I just don't know what that is right now.

**Comment by Lecrapouille** [comment]
I have you tried my v2.x.y branch https://github.com/sebastiandev/zipper/tree/v2.x.y ? I no longer use CMake and my Makefile generates the both libs. I'm now hardly help on this lib I personally dislike CMake so I will only focus on this new branch.

**Comment by potterpg** [comment]
Hi, thanks for your suggestion.
Cmake generated an xcode project, which I played around with, and managed to make it work for my purposes.
However, thanks for pointing me to the newer version, which presumably works seamlessly.
