### ISSUE TITLE
why include minizip &&zlb 

### ISSUE THREAD

**Issue by stan1334** [sebastiandev/zipper#114]
[minizip @ 469fa4b](https://github.com/Lecrapouille/minizip/tree/469fa4bfc8620550db514f940ebc5053b32cf6c9)
[zlib @ 254474d](https://github.com/Lecrapouille/zlib/tree/254474d0dbd0379d39699a74c9b32fb20d484764)

because your ci need more arch，just like x86、arm、aarch。
This kind of project relies on source code that is particularly similar to golang。
i crosscompile arm on x86，once through。

Is there any other reason for this dependency?

@Lecrapouille
@sebastiandev

**Comment by Lecrapouille** [comment]
I did not get your point between submodules and CI with different archs. This project needs them and they are outdated. Else yes the CI is offering the strict minimal job and needs to be improved and converted to googletests ... but on my side, I've no more time to offer on this lib. Therefore pull requests are welcome.
