### ISSUE TITLE
passwords

### ISSUE THREAD

**Issue by chico-depressive** [sebastiandev/zipper#12]
nice lib, have plans to add password anytime soon?

**Comment by sebastiandev** [comment]
ups, sorry for such delay, i was 100% sure I'd replied to this. I dont really have enough time right now to add new logic here, I do appreciate any contribution. Also, there's some stuff going on so there's probably going to be changes here and if that's the case someone might find time to add this feature.
But, ill keep this open and update when necessary.

**Comment by Lecrapouille** [comment]
Reference: https://github.com/sebastiandev/zipper/issues/45
