### ISSUE TITLE
zip folder error

### ISSUE THREAD

**Issue by lemon19900815** [sebastiandev/zipper#121]
if I zip a folder like zlib, the compressed file is not correct.
e.g. on Windows I zip a folder "D:\\workspace\\tech\\zipper\\zlib", the folder has the file "D:\\workspace\\tech\\zipper\\zlib\\contrib\\testzlib\\testzlib.c", then zip the target file result is "zlib\\testzlib.c", but right result is "zlib\\contrib\\testzlib\\testzlib.c". I find the error code on
https://github.com/sebastiandev/zipper/blob/87b14a4b31771ed94ebb3204dc6ed69ad9c78436/zipper/zipper.cpp#L344C16-L344C16
```c++
bool Zipper::add(const std::string& fileOrFolderPath, Zipper::zipFlags flags)
{
    if (isDirectory(fileOrFolderPath))
    {
        std::string folderName = fileNameFromPath(fileOrFolderPath);
        std::vector<std::string> files = filesFromDirectory(fileOrFolderPath);
        std::vector<std::string>::iterator it = files.begin();
        for (; it != files.end(); ++it)
        {
            Timestamp time(*it);
            std::ifstream input(it->c_str(), std::ios::binary);
            std::string nameInZip = it->substr(it->rfind(folderName + CDirEntry::Separator), it->size()); // error code
            add(input, time.timestamp, nameInZip, flags);
            input.close();
        }
    }
```
fix error with this code: `std::string nameInZip = folderName + it->substr(fileOrFolderPath.size(), it->size());`

**Comment by Lecrapouille** [comment]
@lemon19900815 sorry for long delay, the main branch has several issues fixed in the V2 branch or in the fork https://github.com/Lecrapouille/zipper/blob/master/src/Zipper.cpp#L533 the reason is given here https://github.com/sebastiandev/zipper/issues/119
