### ISSUE TITLE
compiling

### ISSUE THREAD

**Issue by alaxmo13** [sebastiandev/zipper#14]
Some functions have been deprecated and they need to be replaced. I tried by my own but I had some problems with VS2017 and I couldn't reach it. Could you update the project with the new functions please? 

Thank you!

**Comment by sebastiandev** [comment]
@alaxmo13 sorry for the delay, I'm not really up to date with the latest c++ stuff, @fbergmann  has been doing a lot more work with it that I. Could you specify those deprecated functions  and the replacement for them?
Thanks

**Comment by fbergmann** [comment]
I am using https://github.com/fbergmann/zipper just fine with VS2017 as well. If you like i can create a new pull request.

**Comment by sebastiandev** [comment]
@fbergmann  yeah lets do that, and I'll merge as soon as it shows up. Thanks!

**Comment by alaxmo13** [comment]
@sebastiandev @fbergmann thank you guys!
