### ISSUE TITLE
Error creating Unzipper object

### ISSUE THREAD

**Issue by Antony007** [sebastiandev/zipper#2]
Hi Sebastian,

I compiled your code in VS2015.  I had to make the following changes to tools.cpp for  VS2015 otherwise it wont compile.

```c++
std::string parentDirectory(const std::string& filepath)
{
	return fs::path(filepath).parent_path().string();
}


std::string currentPath()
{
	return fs::current_path().string();
}


std::vector<std::string> filesFromDirectory(const std::string& path)
{
	std::vector<std::string> files;

	auto folder = fs::path(path);
	auto it = fs::recursive_directory_iterator(folder);
	for (it; it != fs::recursive_directory_iterator(); ++it)
	{
		// file object contains absolute path in the case of recursive iterators
		const auto& file = it->path();
		if (!fs::is_directory(file))
			files.push_back(file.string());
	}	
	
	return files;
}


std::string fileNameFromPath(const std::string& path)
{
	return fs::path(path).filename().string();
}
```
When running the test program, Unhandled exception is raised while unzipping. Exception is raised while creating a Unzipper object.

std::exception at memory location 0x00E7E9C8

**Comment by sebastiandev** [comment]
Hey there,

I don't have VS 2015 right now, but initializing with a filename is pretty straight forward, and no tools.cpp method is involved there. Still, did you verified that those changes return the expected values? im asking because it was pretty tricky back when i used them.

Which test is failing? Is the in-memory zip test passing? Could you provide the whole stack-trace? 

thanks!

**Comment by Antony007** [comment]
Sorry Sebastian,

I had used microsoft's secure functions (fopen_s etc.). I undid that and used #define _CRT_SECURE_NO_WARNINGS 1 .  Now the issue is solved.

**Comment by sebastiandev** [comment]
No problem! Thanks for giving it a try, i hope you find it useful :)

Also if you want to add the conditionals for VS2015 so it works on both
compilers, feel free to send me a pull request and I will add those changes.

Seba.
