### ISSUE TITLE
Add ability to link to static zlib instead of shared one (linux).

### ISSUE THREAD

**Issue by vityafx** [sebastiandev/zipper#22]
Now it links only to dynamic library on linux but I would prefer static one.

Now when I try to use libzipper I have the following errors:

```
undefined reference to `crc32'
undefined reference to `inflate'
undefined reference to `inflateInit2_'
undefined reference to `inflateEnd'
undefined reference to `get_crc_table'
collect2: error: ld returned 1 exit status
```

There is completely no way to override or specify zipper's CMakeLists.txt to link to static version of `zlib`.

**Comment by fbergmann** [comment]
Actually there is, you can manually define `LIBZ_LIBRARY` by passing in the full path to the library to be used. If you specify that cmake option, it will not be overwritten.

**Comment by vityafx** [comment]
I bring my apologizes. Yes, there is a way of overriding LIBZ_LIBRARY and LIBZ_INCLUDE_DIR variables but no matter what I do I get the same result:

```
$ nm libZipper-static.a  | grep crc
                 U crc32
                 U crc32
                 U get_crc_table
                 U crc32
                 U get_crc_table
```

However, the library it is linked to:

```
$ nm thirdparty/thirdparty/src/zlib-installed/lib/libz.a | grep get_crc_table
0000000000000000 T get_crc_table
```

```
$ nm thirdparty/thirdparty/src/zlib-installed/lib/libz.a | grep crc32
crc32.o:
0000000000000094 T crc32
00000000000004f6 t crc32_big
0000000000000c19 T crc32_combine
0000000000000a6d t crc32_combine_
0000000000000c46 T crc32_combine64
00000000000000bf t crc32_little
000000000000000b T crc32_z
                 U crc32
                 U crc32
```

@fbergmann Could you comment this please?

**Comment by fbergmann** [comment]
I think that is actually how it is supposed to work. Once you use the libZipper-static library, you will additionally have to link against your libz.a, and everything will work.

**Comment by vityafx** [comment]
@fbergmann oh, you are right it seems, I have totally forgot how linking static libraries works.. Thank you.
