### ISSUE TITLE
Fork to use latest C++

### ISSUE THREAD

**Issue by sebastiandev** [sebastiandev/zipper#24]
Continuing discussion from #16 in order to decide effort to fix leaks and interface improvements

Yeah I rushed a little with C++17, but the main point was making a fork that would let us have a project that only deals with latest standard without having to worry with old compiler and odd platforms compatibility. Many of the issues we are seeing here are mostly because we decided not to use boost/qt as dependencies because of having compatibility in mind with other platforms. 

My question is, is it worth it to work on a fix for the path management and memory leaks. Or maybe use that time to decide/improve the interface and have a state of the art up to date library?

**Comment by Lecrapouille** [comment]
https://github.com/ctabin/libzippp can inspire you for your API, seems to me that your API can complete it.

I'm not fond of qt/boost and lib dependencies. But there is a lighter lib you can use: POCO https://pocoproject.org/documentation/index.html they have a Path class: https://pocoproject.org/slides/080-Files.pdf

> Many of the issues we are seeing here are mostly because we decided not to use boost/qt

I don't think so, just missing delete in destructor for the moment.

**Comment by GiuseppeCesarano** [comment]
I will make an attempt to port this lib to C++17 using std::filesystem. If i have time i will also try to update the minzip dependency, we're using a 7+ year old version.

**Comment by Lecrapouille** [comment]
@GiuseppeCesarano We can make a branch dev-c++17

**Comment by GiuseppeCesarano** [comment]
I think it's the best approach to make a separate branch

**Comment by Lecrapouille** [comment]
An attempt was made https://github.com/sebastiandev/zipper/tree/dev-modernize
I did not merge it inside the v2.x.y branch. I do not have energy and time to complete all libs with c++17 filesystem.
Wait for pull requests :)
