### ISSUE TITLE
Add more compilation flag

### ISSUE THREAD

**Issue by Lecrapouille** [sebastiandev/zipper#26]
Currently your cmake does not produce lot of compilation flags. Could be nice to add -O2 -W -Wall. 

And why not an option for address sanitizer (do not call with valgrind) ?
CXXFLAGS += -O1 -g -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls
LDFLAGS += -fsanitize=address -fno-omit-frame-pointer -fno-optimize-sibling-calls
LIBS += -static-libstdc++ -static-libasan
ASAN_OPTIONS=symbolize=1 ASAN_SYMBOLIZER_PATH=$(shell which llvm-symbolizer)

Look:
```
----------------------------------------------------------------------
Zipper version 0.9.1
----------------------------------------------------------------------

   Configured on host ''
     host type                       = Linux
     host operating system           = Linux 4.10.0-35-generic
     host CPU architecture           = i686

   General build flags:
     CC                              = /usr/bin/cc
     CXX                             = /usr/bin/c++
     CPPFLAGS                        =  -DLINUX
     CFLAGS                          =  -fno-strict-aliasing -fPIC
     CXXFLAGS                        =  -fno-strict-aliasing -fPIC
     LDFLAGS                         = -L/usr/local/lib

   Zlib library configuration:
     Zlib library                    = /usr/lib/i386-linux-gnu/libz.so
     Zlib include dir                = /usr/include

   Other configuration settings:
     Installation $prefix            = /usr/local
```

**Comment by fbergmann** [comment]
since the option exists that users can pass in these flag (or whatever other flags they want), I do not see a need to have that happen always / or automatically. This can be done by specifying the fags like: CMAKE_CXX_FLAGS, CMAKE_EXE_LINKER_FLAGS or CMAKE_CXX_FLAGS.

**Comment by Lecrapouille** [comment]
ok, so:
```
cmake ..
make CXX_FLAGS="-O2 -Wall -W"
```
That works thanks :) You should really compiled with all compilation warnings: that gives lot of good informations: missing initializers, test with < 0 always false, wrong order in member init.

**Comment by oranja** [comment]
:+1: for `-Wall -O2` and even `-Wextra` (formerly known as `-W`) as sane defaults for release builds.
It's also easy in Windows/MSVC: `/Wall /O2`

**Comment by Lecrapouille** [comment]
I fixed compilation warnings on https://github.com/Lecrapouille/zipper/commit/197753647e95905e09d29c679f580c9ddb6de28a
