### ISSUE TITLE
Writing wrong file name on Linux

### ISSUE THREAD

**Issue by nicvac** [sebastiandev/zipper#32]
Hi, 
thank you for your lib. Very useful!
Issue:
unzipper.extractEntry( "file1.txt", "/tmp" );

Writes a file called /tmp\file1.txt
instead of writing file1.txt in path /tmp

Hi think the problem is here:
./unzipper.cpp:      std::string outputFile = destination.empty() ? name : destination + "\\" + name;

**Comment by Lecrapouille** [comment]
Is the patch made on the develop branch fixes your case (until adding unit/non regression tests) ?
