### ISSUE TITLE
unzipper does not extract folder and files more than one level.

### ISSUE THREAD

**Issue by snahmad** [sebastiandev/zipper#34]

**Comment by ozelcan** [comment]
So i think a have a simillar issue. I have a directory in a zip file, after i decompress it i got files just like named "foldername1\innerfolder1\file.txt". I was expecting a decompressed folder structure not just files. Is there a way to decompress as folder sutructure?
![capture](https://user-images.githubusercontent.com/36914521/48754984-cba24080-eca4-11e8-8e06-1b6b4c910df4.PNG)

**Comment by Lecrapouille** [comment]
Can you give me a short example code ?

**Comment by JackHack96** [comment]
I'm having this issue right now. I have a zip that contains only one folder and inside that folder there are a bunch of files.
If I try to extract everything to a specific path, the library just fails.

```cpp
#include <iostream>
#include "zipper/unzipper.h"

int main()
{
    zipper::Unzipper unzipper("test.zip");
    unzipper.extract();
    if (!unzipper.extract(PATH)) {
        std::cerr << "There was an error while extracting the files from the ZIP archive." << std::endl;
        return -1;
    }
    unzipper.close();
}
```
[test.zip](https://github.com/sebastiandev/zipper/files/7114906/test.zip)

**Comment by Lecrapouille** [comment]
@JackHack96 strange, both functions work well for me :( if I comment `unzipper.extract();` and instead of `PATH` I use "ici" the extracted folder are ok. And also tested with an extra folder depth. Have you an '/' at the end of the dir path ?
```
 tree ici/
ici/
└── test
    ├── test1.txt
    └── test2.txt

1 directory, 2 files
```

With #102 this is the second times people have a different behavior than me. Can you try this following patch:
```
#include <iostream>

    int extractToFile(const std::string& filename, ZipEntry& info)
    {
        int err = UNZ_ERRNO;

        /* If zip entry is a directory then create it on disk */
        if (!makedir(parentDirectory(filename))) // BEFORE PATCH: SILENT ERROR 
        {
           std::cerr << "FAILED makedir" << std::endl;
        }

        /* Create the file on disk so we can unzip to it */
        std::ofstream output_file(filename.c_str(), std::ofstream::binary);

        if (output_file.good())
        {
            if (UNZ_OK == extractToStream(output_file, info))
            {
                std::cerr << "OK extractToStream" << std::endl;
                err = UNZ_OK;
            }

            output_file.close();

            /* Set the time of the file that has been unzipped */
            tm_unz timeaux;
            memcpy(&timeaux, &info.unixdate, sizeof(timeaux));

            changeFileDate(filename, info.dosdate, timeaux);
        }
        else
        {
            std::cerr << "FAILED ofstream" << std::endl;
            output_file.close();
        }

        return err;
    }
```

What branch do you use, What OS ?

**Comment by Lecrapouille** [comment]
@JackHack96 In fact can you replace your zipper folder by this one ? Recompile it and install it and re-run your test. I added more logs.

[zipper.zip](https://github.com/sebastiandev/zipper/files/7117369/zipper.zip)

**Comment by srroger** [comment]
Hello, I have the same issue (1.0.3)
In fact, the issue comes from when the zip file has been created with an external tool ( and the zip contains a folder)


The extraction fails and return false (without an exception):
`unzipper.extract();`


However, if the zip files has been created with zipper (and the zip contains a folder), then the extraction works perfectly...

**Comment by v77777** [comment]
i also have this problem,but i can sloving this problem like 
`Unzipper unzipper(src_file);
  std::vector<ZipEntry> entries = unzipper.entries();
  for (ZipEntry entry : entries)
  {
    unzipper.extractEntry(entry.name, des_folder);
  }`

**Comment by Lecrapouille** [comment]
Closed since working on branch 2.x.y. Please reopen this ticket in not fixed
