### ISSUE TITLE
Error when unzipping

### ISSUE THREAD

**Issue by lukeeey** [sebastiandev/zipper#35]
Fixed the segfault, but now i get another error
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error 18446744073709551514 opening internal file 'release-notes.txt' in zip
Aborted (core dumped)

```

**Comment by Lecrapouille** [comment]
When you said `Fixed the segfault` what exactly fixed your segfault ? Is this related to another closed issue ?

**Comment by lukeeey** [comment]
I really cant remember

**Comment by Lecrapouille** [comment]
So I close this ticket ? Feel free to open it again once you remember the test case producing this error.

**Comment by lukeeey** [comment]
Yeah its fine to close, but just incase you didnt know once the repository owner has closed an issue the person who originally created it cant open it again.

**Comment by Lecrapouille** [comment]
I did not know ! But you can still post a comment the owner will open it back.
