### ISSUE TITLE
Windows won't zip directories

### ISSUE THREAD

**Issue by pauleibye** [sebastiandev/zipper#36]
Had an issue zipping folders from windows. Found that the GetFileAttributes call in opendir in dirent.c will cast a std::string to a stringw which doesnt ever find the file as std::string is ascii and a stringw is unicode. Changing the code to always call the ascii macro fixed the issue: 
```
DIR *opendir(char const *name)
{
    DIR     *result =   NULL;
    DWORD   dwAttr;

    /* Must be a valid name */
    if( !name ||
        !*name ||
        (dwAttr = GetFileAttributesA(name)) == 0xFFFFFFFF)
    {
        errno = ENOENT;
    }
```
I would ask to do a pull request or something, but it looks like the last one that's open is from a year ago so I'd guess this project is dead... but for any windows people who run into this issue this should fix it.

**Comment by Lecrapouille** [comment]
Is the patch made on the develop branch fixes your case (until adding unit/non regression tests) ?

**Comment by pauleibye** [comment]
@Lecrapouille I'd guess so, that's the fix that I did for my project and it worked.
