### ISSUE TITLE
Failing to archive binary files

### ISSUE THREAD

**Issue by alexbala** [sebastiandev/zipper#4]
Hi Sebastian,

I compiled your code in VS2015 after I've made the changes Antony007 said about in the issue he opened. 
It's working properly (compressing and uncompressing) for text files, but I had problems whenever I chose files like dlls, libs, exes, chms, etc. They were incomplete (much smaller in size) after archive.
I've made it working by specifying the 'binary' flag when you create the ifstreams and ofstreams:

```
bool Zipper::add(const std::string& fileOrFolderPath, zipFlags flags)
{
   ...
   std::ifstream input(f, std::ifstream::binary);
   ...
   std::ifstream input(fileOrFolderPath, std::ifstream::binary);
   ...
}
```

and
```

int extractToFile(const std::string& filename, ZipEntry& info)
{
   ...
   std::ofstream output_file(filename, std::ofstream::binary);
   ...
}
```

Maybe you could test it for binary files too and make the necessary modificationsif it doesn't work on VS2013.

**Comment by sebastiandev** [comment]
Hey, yep i missed that one. good catch. Wanna make a pull request for this change?

Thanks!

**Comment by alexbala** [comment]
I'm new to github. I've made an account just to write the previous comment :) I don't know how to make a pull request.

**Comment by sebastiandev** [comment]
ah no problem, i'll make those changes and let you know!
thanks!

**Comment by Blacklands** [comment]
Hey,
Just wanted to ask, has this been fixed in the "master" branch yet? I see there's a pull request apparently dealing with it; has that been merged in?
If not, I could try to make all those changes and do a pull request myself, if you want (never did this before though).
Would be happy about a reply, since I'm looking forward to using this library soon! :)

**Comment by fbergmann** [comment]
I already have a pull request pending that includes the binary streams ... so i don't think another pull 
request is needed at this point. 

cheers
frank

**Comment by Blacklands** [comment]
I saw that one, I just wasn't sure if it was really related to the problem, and if it was already merged in or not (still new to GitHub, to my defense).
Thanks for letting me know this, though! I hope it'll get merged in sometime soon.

**Comment by sebastiandev** [comment]
merged! sorry i didn't notice the pr before. enjoy :)
