### ISSUE TITLE
This breaks if I include this lib as a sub directory

### ISSUE THREAD

**Issue by mez** [sebastiandev/zipper#42]
https://github.com/sebastiandev/zipper/blob/01b3566b36ae2a22573172a18f24f9c259e902b2/CMakeLists.txt#L388

replacing it with `CMAKE_CURRENT_LIST_DIR` fixes this issue.

**Comment by Lecrapouille** [comment]
May you create a PR ? @uberferg is this fix ok for you ? I do not know CMake.

**Comment by mez** [comment]
Yes I can create a PR
