### ISSUE TITLE
Download folder minizip is empty

### ISSUE THREAD

**Issue by AlvinZhangH** [sebastiandev/zipper#50]
There are files in folder minizip @ e3a8cb7 in https://github.com/sebastiandev/zipper, but download folder minizip is empty.

**Comment by Lecrapouille** [comment]
@AlvinZhangH did you made
```
git clone git@github.com:sebastiandev/zipper.git --recurse-submodules
```

for cloning? Note: github makes empty submodules when you click on "download zip" button
