### ISSUE TITLE
unzipper.extractEntry works but returns false... Why ???

### ISSUE THREAD

**Issue by KevLoq** [sebastiandev/zipper#53]
Dear you,
here is my code
```C++
if( !unzipper.extractEntry( entry.name, GetFullPathToOutputDir() ) )
{    // I do not like this but it works
   LOG( WARNING ) << "zipper lib returns extraction failed, whereas it works... for " << entry.name;
}
```
it works, the file are properly unzipped and located at the right location. But extractEntry returns false for every extracted file. 
I do not like it as it could hide some problem or defect in the extracted file ... I do not know exactly why but I do not like it.

**Comment by Lecrapouille** [comment]
Ok I'll look at it. Which archi do you use ? Windows ? Linux ?

**Comment by Lecrapouille** [comment]
@KevLoq I pushed a fix. This made automatically close the ticket. Tell me if that fixed you the problem else reopen it.

I have to seriously write unit tests.

By the way @sebastiandev @fbergmann Sorry I'm nut in English, but it looks like your methods `extractEntryToStream, extractEntryToMemory` shall be named `extractEntryFromStream, extractEntryFromMemory` ?

**Comment by KevLoq** [comment]
Thank you
I will try it on the coming days

Tu es francais ?

**Comment by Lecrapouille** [comment]
@KevLoq Yes I'm Frenchman and I'm not the author of this lib I'm just helping.
