### ISSUE TITLE
new exception in initWithStream (zipper.cpp/unzipper.cpp) 

### ISSUE THREAD

**Issue by samuelseu** [sebastiandev/zipper#56]
the stream.tellg() may return -1, in this case, the size may be 0xffffffff after converting to a unsigned int (size_t). Then the code would try to allocate a large number of memory, the size of new memory is 0xffffffff. It would cause new exception.

there's no need to convert the size into size_t, as there's judgement below.

```
bool initWithStream(std::iostream& stream)
		{
			m_zipmem.grow = 1;

			stream.seekg(0, std::ios::end);
			size_t size = (size_t)stream.tellg();
			stream.seekg(0);

			if (size > 0)
			{
				m_zipmem.base = new char[(size_t)size];
				stream.read(m_zipmem.base, size);
			}

			fill_memory_filefunc(&m_filefunc, &m_zipmem);

			return initMemory(size > 0 ? APPEND_STATUS_CREATE : APPEND_STATUS_ADDINZIP, m_filefunc);
		}
 
```

**Comment by Lecrapouille** [comment]
Sorry I did not see the notification of your issue. I had already had to deal with this kind of boring casting. Ok I'll fix that.

**Comment by Lecrapouille** [comment]
Fixed ! Please check if everything is alright !
