### ISSUE TITLE
CMakeLists.txt should set minimum required CMake version to 3.0

### ISSUE THREAD

**Issue by OliverHaag** [sebastiandev/zipper#57]
The old cmake_minimum_required(VERSION 2.6) is causing zipperTargets-*.cmake to contain absolute paths, making it unusable on machines other than the one the package was built on.

Additionally zipper could use the newer namespacing-style. I've patched that into zipperConfig.cmake.in, but it could probably be done in a nicer way:
[changes.txt](https://github.com/sebastiandev/zipper/files/4886411/changes.txt)

**Comment by Lecrapouille** [comment]
Thanks I have to seriously learn CMake

**Comment by Lecrapouille** [comment]
Merged ! Please check if everything is alright !
