### ISSUE TITLE
Use AES as default.

### ISSUE THREAD

**Issue by sarahkittyy** [sebastiandev/zipper#59]
ZipCrypto is an outdated and insecure encryption method, which the password protected zipping uses. Consider defining `HAVE_AES` when compiling minizip to use AES encryption instead.

For now, in your root CMakeLists.txt, you can use

```cmake
add_definitions(-DHAVE_AES)
```
to circumvent this :)

**Comment by Lecrapouille** [comment]
Hi ! Thanks ! Can you provide a pull request ?

**Comment by Lecrapouille** [comment]
Thanks ! This fix https://github.com/sebastiandev/zipper/issues/87
