### ISSUE TITLE
Add MD5 with release to check downloaded file

### ISSUE THREAD

**Issue by kriegalex** [sebastiandev/zipper#61]
A nice to have thing when the library is installed in an automated script.

**Comment by kriegalex** [comment]
MD5SUM 1.0.1
```
42396a2fe8d5654eca3cd77bebd7666a  zipper-1.0.1.tar.gz
2294d0f39ffdd97fc18fd7d5ffe8b9ca  zipper-1.0.1.zip
```
MD5SUM 1.0.0
```
4333987f299eeb90b3a7403bd8ccdb1a  zipper-1.0.0.tar.gz
e094ce44aafbd765bfcea8e264753ad9  zipper-1.0.0.zip
```

**Comment by Lecrapouille** [comment]
I'm not sure to follow you. You want to have the md5 of the zip file ? or having a file inside the zip containing the md5 of the zip file ? For the 1st question, you can simply include (copy/paste) a md5.c in your project to compute md5 of your zip. For the 2nd question, if you change the file containing the md5sum of the zip including this file, the real md5sum will be different to the value stores in the file :(

**Comment by kriegalex** [comment]
Hello,
Please have a look at this release example from ITK to see what I mean (MD5SUMS file) : https://github.com/InsightSoftwareConsortium/ITK/releases/tag/v5.1.0

This is by now a common practice, very useful in automated install scripts. hard-coding things in the script is not that good.

When you download a release file, it is nice when the MD5 is available with the release, on a public URL.

**Comment by kriegalex** [comment]
Sorry I cannot help you more on CD/CI part of it, I'm not familiar with Github CD/CI's integration possibilities

**Comment by Lecrapouille** [comment]
I'll not implement it, sorry.
