### ISSUE TITLE
Zipper release files don't contain minizip code

### ISSUE THREAD

**Issue by kriegalex** [sebastiandev/zipper#62]
Simply extracting a downloaded .tar.gz file doesn't allow to build zipper, without having to clone minizip.

Since minizip is not versioned, it is hard to do it properly via release files. 

Two things can happen to improve this:
1) Either zipper contains minizip in the release file
2) Or a versioned zipper commit (like 1.0.1) points to a specific release of minizip (like 1.0.0). Then one can download both release files and do the job manually in the script (extract minizip inside zipper).

**Comment by kriegalex** [comment]
For one, one must `clone --recursive` and switch to the desired tag (i.e. 1.0.1)

**Comment by Lecrapouille** [comment]
Hi! Thanks this is not the first opened issue concerning this point. This is more an issue of GitHub which makes releases without including submodule. Same idea when downloading the zip of the master instead of git cloning --recursive

**Comment by Lecrapouille** [comment]
https://github.com/sebastiandev/zipper/issues/50

**Comment by kriegalex** [comment]
Maybe you can at least version minizip then (see my option 2), and have coherent versioning between both project, so we can download the correct releases of each and stitch them together. It will also improve your workflow of managing them both :)

**Comment by Lecrapouille** [comment]
https://stackoverflow.com/questions/34719785/how-to-add-submodule-files-to-a-github-release

**Comment by Lecrapouille** [comment]
minizip git submodule is hardly upgraded since zipper authors did not follow evolutions and now we are stuck with an old SHA1.
