### ISSUE TITLE
Static and Shared uses same output name in CMake

### ISSUE THREAD

**Issue by Togtja** [sebastiandev/zipper#63]
While the static get called staticZipper and shared Zipper internally. However, when the are to output the library files the staticZipper gets [renamed](https://github.com/sebastiandev/zipper/blob/master/CMakeLists.txt#L357) to Zipper.
This causes a `ninja: error: build.ninja:5910: multiple rules generate Binaries/Lib/Zipper.lib [-w dupbuild=err]`  Ninja Generator/CMake error when trying to build both the shared and the static library

The easy fix is, of course, to have them named differently/remove the rename.

Don't know if this is only caused on the newer version of CMake, as I am running 3.18.0 or if the visual studio generator allows this?

EDIT:
This was on Windows, so it might behave differently on Unix

**Comment by Lecrapouille** [comment]
@Togtja  I did not check the link in your 1st comment. It refers on unrelated commit. In fact the change has been made here 
https://github.com/sebastiandev/zipper/commit/1e95b5bd2185422b17d1f1f2f7d3f6e92b69c8bd
I dunno if that can help you.

**Comment by razaqq** [comment]
same issue here `ninja: error: build.ninja:1067: multiple rules generate ThirdParty/zipper/Zipperd.lib [-w dupbuild=err]`

**Comment by Lecrapouille** [comment]
@Togtja  @razaqq Sorry I'm not good with Window and with CMake :) Since this PR #66 is fixing this, can I close this ticket ?
