### ISSUE TITLE
Zlib as a submodule

### ISSUE THREAD

**Issue by Togtja** [sebastiandev/zipper#69]
After #68 got integrated, this opens up for getting zlib as a submodule, I do not know if this is wanted, would make it easier to build on Windows where zlib is not standard?
I made a personal branch where I added zlib to Zipper [found here](https://github.com/Togtja/zipper/tree/submodule_zlib)

I did a very [minor change](https://github.com/Togtja/zlib/commit/9a5eeeb6204f93f75f81bdb2413be0a55005090e) to the original zlib library, to stop the renaming of `zconf.h` in out of source build. 

As the submodule works now, it installs the zlib to the build/zlib_bin (or more accurately ` ${CMAKE_CURRENT_BINARY_DIR}/zlib_bin`). As of now, I know it works on Windows, and I plan on testing it on Ubuntu later. Just want to know if this is something that could be wanted?

**Comment by Lecrapouille** [comment]
I like the idea this also may help me to close this https://github.com/sebastiandev/zipper/issues/54

**Comment by Lecrapouille** [comment]
@Togtja In the "develop" branch I updated appveyor to fix broken keys https://github.com/sebastiandev/zipper/commit/9c8caeb9f0ff6194eaac893b047eb48117369db5 but still stuck with:
```
-- Looking for gzopen in LIBZ_LIBRARY-NOTFOUND
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIBZ_LIBRARY
    linked by target "cmTC_9fd8d" in directory C:/projects/zipper/build/CMakeFiles/CMakeTmp
CMake Error at C:/msys64/mingw64/share/cmake-3.17/Modules/CheckLibraryExists.cmake:67 (try_compile):
  Failed to generate test project build system.
Call Stack (most recent call first):
  CMakeLists.txt:155 (check_library_exists)
```

It looks like you have fixed that before this ticket. I would like to know what missing pacman I have to add or if zlib should be compiled manually.

**Comment by Lecrapouille** [comment]
PS: @Togtja I meant for Windows MSYS2 (since Linux and MacOS X they work perfectly)

**Comment by Togtja** [comment]
#68 Should not change the behaviour on any platform, as it just uses the internal CMake script to find Zlib. I find it really wierd that it is looking for `LIBZ_LIBRARY` that should have be removed on #68 pull request

**Comment by Togtja** [comment]
I am currently working on making zlib a module it works on Windows and Linux for static, but shared libary I encounter an error. So will work a bit on it today

**Comment by Lecrapouille** [comment]
#68 Should not change the behaviour on any platform, as it just uses the internal CMake script to find Zlib. I find it really wierd that it is looking for LIBZ_LIBRARYthat should have be removed on #68 pull request

mmmh ! that makes me remind that we've committed on the develop branch but initially the appveyor was configured to build the master branch. I changed it with my last change on the dev branch but on the CI log it still building the master branch (what happened to the dev ??).

**Comment by Lecrapouille** [comment]
I merged dev into master but for the appveyor (CI for Windows) I know I cannot download libz with pacman I dunno where this lib can be installed I guess to be compiled manually.

**Comment by Togtja** [comment]
I am running Visual Studio Build Tools 2019. However, I edit code in VS Code, and I use WSL to run Ubuntu 20.04 with GCC 9 and 10. I also have an actual Ubuntu machine, but I only bother to boot it up when doing final testing, as WSL works 99% of the time as a Ubuntu machine.

Update on this:
Building static works, but I can't build shared... unless... I build static first, then I build shared.
The error I get stuck with when building shared is it can't find zlibd (similar error on Linux)
```
error: 'zlib_install/lib/zlibd.lib', needed by 'Zipperd.dll', missing and no known rule to make it
```
So when I build static, I get no issues, and it successfully builds zlib, and then it will find the needed zlibd.lib if i build shared after that. I am not certain why this happens

**Comment by Lecrapouille** [comment]
I'm sorry I know few about CMake, I was never really interested by this complex syntax on a file which is finally as long as a hand made Makefile just for generating ... a makefile. For the few I used I realized that you cannot create shared and static library. That is why the original authors gave a different name for the static lib. This is non sense for me ! Using Gnu Makefile I have this kind of error is when http://make.mad-scientist.net/papers/how-not-to-use-vpath/

**Comment by kriegalex** [comment]
If zlib is shipped with libzipper as a submodule, it would be nice to add a cmake variable to allow to use a system installed library. As an example, see VTK:

`VTK_USE_SYSTEM_ZLIB`

**Comment by yhyu13** [comment]
@Lecrapouille I encounter a strange bug that would fail the unit testing with Zlib that is installed from GetGnuWin32 on Win10x64.

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Zipper-test.exe is a Catch v1.5.6 host application.
Run with -? for options

-------------------------------------------------------------------------------
Scenario: zipfile feed with different inputs
     Given: A Zip outputed to a file
      When: a file containing 'test file compression' is added and named
            'test1'
-------------------------------------------------------------------------------
D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\file_zip_test.cpp(15)
...............................................................................

D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\file_zip_test.cpp(27): FAILED:
due to unexpected exception with message:
  Error adding 'test1.txt' to zip

-------------------------------------------------------------------------------
Scenario: zipfile feed with different inputs
     Given: A Zip outputed to a file
      When: a stringstream containing 'test string data compression' is added
            and named 'strdata'
-------------------------------------------------------------------------------
D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\file_zip_test.cpp(15)
...............................................................................

D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\file_zip_test.cpp(159): FAILED:
due to unexpected exception with message:
  Error adding 'strdata' to zip

-------------------------------------------------------------------------------
Scenario: zip vector feed with different inputs
     Given: A Zip outputed to a vector
      When: a file containing 'test file compression' is added and named
            'test1'
-------------------------------------------------------------------------------
D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\memory_zip_test.cpp(14)
...............................................................................

D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\memory_zip_test.cpp(21): FAILED:
due to unexpected exception with message:
  Error adding 'test1.txt' to zip

-------------------------------------------------------------------------------
Scenario: zip vector feed with different inputs
     Given: A Zip outputed to a vector
      When: a stringstream containing 'test string data compression' is added
            and named 'strdata'
-------------------------------------------------------------------------------
D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\memory_zip_test.cpp(14)
...............................................................................

D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\memory_zip_test.cpp(121): FAILED:
due to unexpected exception with message:
  Error adding 'strdata' to zip

-------------------------------------------------------------------------------
Scenario: zip vector feed with different inputs
     Given: A Zip outputed to a vector
      When: a file containing 'test file compression' is added and named
            'test1' in subdirectory 'subdirectory'
-------------------------------------------------------------------------------
D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\memory_zip_test.cpp(14)
...............................................................................

D:\GitWorkZone-3rdParty\zipper-collection\zipper\test\memory_zip_test.cpp(168): FAILED:
  {Unknown expression after the reported line}
due to unexpected exception with message:
  Error adding './subdirectory/test1.txt' to zip

===============================================================================
test cases: 2 | 2 failed
assertions: 6 | 1 passed | 5 failed
```

The MSVC debugger points to this line in minizp that invokes a zlib method [here](https://github.com/Lecrapouille/minizip/blob/7619140097aaba8bd49659cb9c4878c4b1dcac30/zip.c#L1258)

I've tried to build @Togtja's branch with zlib submodule that the problem is gone.

**Comment by Lecrapouille** [comment]
@yhyu13 our minizip reference is dated to 2016. After the API is broken. Not sure how to deal with fresh minizip version.

**Comment by Togtja** [comment]
As #93 has been merged I will close this.
As to the concern if it is possible to use system defined zlib. It should be.
It uses the [FindZLIB](https://cmake.org/cmake/help/latest/module/FindZLIB.html) cmake command to determin if you already have it in the system. If not then it will attempt to build the submodule
