### ISSUE TITLE
Compile error: zipper/defs.h:35:24: fatal error: filesystem: No such file or directory

### ISSUE THREAD

**Issue by usagi** [sebastiandev/zipper#7]
```
.../zipper/defs.h:35:24: fatal error: filesystem: No such file or directory
   #include <filesystem>
                        ^
```

Why `#include <filesystem>`? It's the C++1z std library but the README in the zipper wrote `"using the latest C++11"`. Don't you wrote the wrong the C++ standard specification level in the README? I cannot compile the zipper using cmake with default `-std=c++11` option.

-----

Environment: msys2 + mingw-w64 / g++-6.1.0 / cmake-3.6.1 / ninja-1.7.1
Rev: 7d795d7 ( the latest current master )

**Comment by fbergmann** [comment]
Unfortunately the stl filesystem API is not yet supported by the STL of clang or g++. That is why I added additional filesystem choices, going with either boost or qt core.

**Comment by sebastiandev** [comment]
@usagi were you able to make it work? can i close this?

**Comment by sebastiandev** [comment]
This can be solved by using boost or qt filesystem classes. In a future PR we might include @fbergmann changes to make it old c++ compatible.
