### ISSUE TITLE
Remove ability to accidentally create empty zip

### ISSUE THREAD

**Issue by Togtja** [sebastiandev/zipper#75]
The `std::istream`constructors `add(std::istream& source, ...` allow us to do:
```cpp
    std::ifstream inp("test.txt");
    zipper::Zipper zip("test.zip");
    zip.add(inp);
    zip.close();
```
However, since `nameInZip` is not specified, the `test.zip` folder just becomes empty. I believe the `nameInZip` should **not** be optional.

**Comment by Lecrapouille** [comment]
@Togtja Sorry for the long delay ! Now prototypes are:
```
bool add(std::istream& source, const std::tm& timestamp, const std::string& nameInZip, zipFlags flags = Better);
bool add(std::istream& source, const std::string& nameInZip, zipFlags flags = Better);
```

Is this what you suggested ?
