### ISSUE TITLE
Add a .clang-format file

### ISSUE THREAD

**Issue by GiuseppeCesarano** [sebastiandev/zipper#79]
I'm trying to work a bit on this library, and i noticed an absence of a `.clang-format` file that defines a code style. Could we make one so it's easier for contributors to keep a consistent style while working on the changes?

**Comment by Lecrapouille** [comment]
Why not. I personally I never had usage of clang-format since I use emacs :) M-x indent-region and M-x untabify

**Comment by Lecrapouille** [comment]
https://github.com/sebastiandev/zipper/pull/82 I'll cherry pick to other branches
