### ISSUE TITLE
Can't provide password to unzipper with vector input 

### ISSUE THREAD

**Issue by xd009642** [sebastiandev/zipper#86]
I have a passworded zip as subset of a larger binary blob and would like to be able to extract elements without having to serialize just that subset to disk first. Is there a reason why a password can't be provided for the unzipper constructors with the stream or vector?

If it is possible I also don't mind doing the PR :smile:

**Comment by Lecrapouille** [comment]
Hi ! Thanks I gonna check if I can add it

**Comment by Lecrapouille** [comment]
@xd009642 I made a fix on the develop branch. Tell me if this ok for you.
