### ISSUE TITLE
Error encrypted archive

### ISSUE THREAD

**Issue by dmitriym09** [sebastiandev/zipper#87]
Hello! Thanks for lib!

I have a problem:

Created encrypted archive:

```
#include <iostream>
#include <fstream>
#include <sstream>

#include <zipper/zipper.h>
#include <zipper/tools.h>

using namespace std;
using namespace zipper;

int main(int, char **)
{
    string zipname("1.zip");
    string password("123");

    std::stringstream myString;
	myString << "Lorem ipsum!" << std::endl;

    Zipper zipper(zipname, password);
    zipper.add(myString, "Test1");

    zipper.close();

    return 0;
}

```

Build:

```
g++ main.cpp -W -Wall -I/usr/local/include -L/usr/local/lib -lZipper -o stream-zipper
```

Execute:

```
./stream-zipper && echo 'ok'

ok
```

Unpack:

```
7z e 1.zip 

7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,4 CPUs Intel(R) Core(TM) i3-4130 CPU @ 3.40GHz (306C3),ASM,AES-NI)

Scanning the drive for archives:
1 file, 135 bytes (1 KiB)

Extracting archive: 1.zip
--
Path = 1.zip
Type = zip
Physical Size = 135

    
Enter password (will not be echoed):
ERROR: Wrong password : Test1
            
Sub items Errors: 1

Archives with Errors: 1

Sub items Errors: 1

```

**Comment by Lecrapouille** [comment]
Hi ! Yes I tried your code and I get the same issue. I know this lib has a serious miss of unit test and non-regression tests. Password have been recently https://github.com/sebastiandev/zipper/commit/3d1ef500c66869be548b86f080945cd2b613f7f8

**Comment by Lecrapouille** [comment]
When doing in your code:
```
Unzipper unzipper("1.zip", "123");
unzipper.extract();
unzipper.close();
```
I have the correct content (else I could fix silent error).

**Comment by Lecrapouille** [comment]
I made some fixes on the development branch but for the moment, you can extract the zip with an external tool, you have only use the library. I'll try to understand why.

**Comment by Lecrapouille** [comment]
I gave a try on the application inside the minizip folder with the same issue :( This is a too old version.

**Comment by Lecrapouille** [comment]
@dmitriym09 Fixed by https://github.com/sebastiandev/zipper/issues/59
Can you try if this is working for you ? On the develop branch
