### ISSUE TITLE
Remove exception

### ISSUE THREAD

**Issue by Lecrapouille** [sebastiandev/zipper#88]
Confusing API: either return false or throw exception. We should use a single poison :)
When returning false could be nice to have a sterror/errno method to return a human readble error message.

**Comment by Togtja** [comment]
If we want to do it more C++, then C. We can model it after the std::filesystem calls.
Where you can give in an std::error_code that holds this information.
```cpp
Unzipper zipfile("example.zip");
std::error_code err;
if(!zipfile.extract(err) || err != 0){
     //Something went wrong
}
```
This I belive I can start to implement that, but I am not familliar enough with the implementation of the C style `getLastError` .. etc

**Comment by Lecrapouille** [comment]
Closing since implemented on Unzipper for the v2.x.y branch. In gestation: the Zipper classe
