### ISSUE TITLE
Wrong dates of archived files

### ISSUE THREAD

**Issue by alexbala** [sebastiandev/zipper#9]
Hi Sebastian,

The information about the files that are added to an archive are not preserved. For example I create an archive, then decompress a file. The decompressed file has a date, let's say: 12/14/1657.

I compared the 'add' function from zipper.cpp with the 'main' function from minizip.
The difference is that the 'add' function doesn't contain

`/* Get information about the file on disk so we can store it in zip */
filetime(nameInZip.c_str(), &zi.tmz_date, &zi.dosDate); 
`

I've added this line and it's working properly now. 

Can you test this and make the necessary changes?

**Comment by sebastiandev** [comment]
Hey, sorry for the delay. Is this windows only? 

Could you please make a pull request with your change, considering linux and windows?

Thanks!
