### ISSUE TITLE
Problem with add method after calling password constructor

### ISSUE THREAD

**Issue by kamil11145** [sebastiandev/zipper#90]
I have problem with add method after calling constructor with password argument. The program "freeze". In debug in go to line zipper.add and doesn't response. Moreover if I execute this code without password parameter everything works fine.

libminizip-dev version (1.1-8build1).
zlib1g-dev version (1:1.2.11.dfsg-0ubuntu2)
Ubuntu 18.04.5 LTS 

```
#include <fstream>
#include <zipper/zipper.h>
using namespace std;
using namespace zipper;

int main()
{
    string zipname("1.zip");
    string password("123");
    std::stringstream myString;
	myString << "Lorem ipsum!" << std::endl;
    Zipper zipper(zipname, password);
    zipper.add(myString, "Test1");		//program freeze here if I pass password parameter. Without password working well.
    zipper.close();
    return 0;
}
```

**Comment by Lecrapouille** [comment]
@kamil11145 To be sure to understand you: `zipper.add(myString, "Test1");` does not take any password as param, only the one provided in the constructor is enough. I copied/pasted your current code 'as it' and it is running well (the return 0 is reached). I have a Debian 10. I tried with g++-8.3 and clang++-7, valgrind does not complain. Continuous integration uses your Ubuntu version. You may try to add https://github.com/bombela/backward-cpp to see the stack trace. How have you compiled zipper : what flags have you passed to cmake, which sha1 + branch have you used for downloading zipper ?

**Comment by kamil11145** [comment]
Hi!
Yes, I understand that the password only go to constructor. I trying run code "as it" and the program just stopped in place which I mark.

What's more funny this code working excellent when I delete password parameter (then I get the correct archive and return 0):
Zipper zipper(zipname, password);	-> 	Zipper zipper(zipname);

I have gcc version 7.5.0

I have done all steps from README:

sudo apt-get install zlib1g-dev
git clone --recursive https://github.com/sebastiandev/zipper.git  # to get zipper and minizip submodule
cd zipper
mkdir build
cd build
cmake ../
make
sudo make install

(no errors)

I would try on other machine tomorrow and change compiler. I will be back with feedback :)!

**Comment by kamil11145** [comment]
I change gcc for newest version (9.3) and...the problem still exists.
I make a little modification which print me additional information and found out where exactly my program "hangs up". It happen when the method "zipOpenNewFileInZip3_64" is calling. I call this function with below parameter:
nameInZip: Test1, password: 123, flags: 16

bool add(std::istream& input_stream, const std::tm& timestamp,
         const std::string& nameInZip, const std::string& password, int flags)
{
printf("nameInZip: %s, password: %s, flags: %d \n",nameInZip, password, flags);

(...SKIP CODE WHICH I DIDN'T TOUCH. I ONLY ADD A FEW PRINTS...)

printf("BEFORE CRC \n");
            getFileCrc(input_stream, buff, crcFile);
printf("AFTER CRC\n");
            err = zipOpenNewFileInZip3_64(m_zf,
                                          nameInZip.c_str(),
                                          &zi,
                                          NULL,
                                          0,
                                          NULL,
                                          0,
                                          NULL /* comment*/,
                                          (compressLevel != 0) ? Z_DEFLATED : 0,
                                          compressLevel,
                                          0,
                                          /* -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY, */
                                          -MAX_WBITS, DEF_MEM_LEVEL, Z_DEFAULT_STRATEGY,
                                          password.c_str(),
                                          crcFile,
                                          zip64);
printf("AFTER ZIP OPEN NEW FILE IN ZIP\n");

The program output is:
nameInZip: Test1, password: 123, flags: 16 
BEFORE CRC
AFTER CRC

...so it didn't go further (then we will see AFTER ZIP OPEN NEW FILE IN ZIP in console).
Any idea which parameter of that function could be wrong? I check it twice and it looks good. Or what I could have wrong in my system?

**Comment by kamil11145** [comment]
Success!
Your code working excellent! I give you a star, that's all what I can :)!

To everyone in the future who will face similar problem the solution is to compile this program from the sources. I copied sources (zipper and minizip path) to my project and adjust this code to my program directly (I only had to delete function which were prepared for windows and of course replace all #includes <> for ""). While compiling don't forget to add -lz library. That's it!

Thank you @Lecrapouille for help :)! Great job!

**Comment by Lecrapouille** [comment]
@kamil11145 Your install is ok. In case of doubt, you can give a try within a Docker (download a Ubuntu Docker + redo zipper clone + install).

For what I understand, our project is not faulty (for this case :). I think your system is "messed up" with installed libraries and probably you are linking with the bad zip library (probably installed with `apt-get` or alternative installer), that is why `zipOpenNewFileInZip3_64` failed up. When building your application inside the "code source" I think you are using the good one and this is working. You can check your LD_LIBRARY_PATH and/or do a `apt-get remove xxx`.

When you said `I only had to delete function which was prepared for windows and of course replace all #includes <> for "")` there is the more easy way if you are using Makefile: do not touch zipper code, keep using original #include and inside your Makefile use `-I<path/to/zipper/include>` and `VPATH = <path/to/zipper/src>`.
