### ISSUE TITLE
Oversized archive after zipping

### ISSUE THREAD

**Issue by tokarevvit** [sebastiandev/zipper#91]
Hello!
Recently I have reached an archieve with size 36Mb but size of the file inside the archieve was only 18.4Mb.
Why could it happen?
The archieve is avaliable by the link below:
https://drive.google.com/file/d/1YMAqL4N1gX-QRAydCacH3INPwHtql2QV/view?usp=sharing

I use Linux Ubuntu 18.04.

**Comment by Lecrapouille** [comment]
@tokarevvit Hi ! To be sure, can you give me the code you have used?

**Comment by tokarevvit** [comment]
This archieve has previously writed data at the beginning.
I've found an error in my code that made such situation.

**Comment by Lecrapouille** [comment]
Yes we can insert several times the same file. I dunno if it was desired by original authors but I would like to fix it https://github.com/sebastiandev/zipper/issues/89
